## Setup

In [23]:
from pathlib import Path
import pandas as pd

## Exploratory Data Analysis

In [24]:
proj_root = Path.cwd()
if proj_root.name == "src":
    proj_root = proj_root.parent

train_data = pd.read_csv(proj_root / "data" / "Train.csv")
test_data = pd.read_csv(proj_root / "data" / "Test.csv")

C:\Users\foste\AppData\Local\Temp\ipykernel_484\261909218.py:5: DtypeWarning: Columns (26: Monthly_Balance) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv(proj_root / "data" / "Train.csv")

In [25]:
print(f"Train shape: {train_data.shape}")
print(f"Test shape: {test_data.shape}")

display(train_data.head())
train_data.info()

display(test_data.head())
test_data.info()

Train shape: (100000, 28)
Test shape: (50000, 27)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  str
 1   Customer_ID               100000 non-null  str
 2   Month                     100000 non-null  str
 3   Name                      90015 non-null   str
 4   Age                       100000 non-null  str
 5   SSN                       100000 non-null  str
 6   Occupation                100000 non-null  str
 7   Annual_Income             100000 non-null  str
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  str
 13  Type_of_Loan              88592 non-null   str
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   str
 16  Changed_Credit_Limit      100000 non-null  str
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  str
 19  Outstanding_Debt          100000 non-null  str
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   str
 22  Payment_of_Min_Amount     100000 non-null  str
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   str
 25  Payment_Behaviour         100000 non-null  str
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  str
dtypes: float64(4), int64(4), object(1), str(19)
memory usage: 21.4+ MB

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance
0,0x160a,CUS_0xd40,September,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,2022.0,Good,809.98,35.030402,22 Years and 9 Months,No,49.574949,236.64268203272135,Low_spent_Small_value_payments,186.26670208571772
1,0x160b,CUS_0xd40,October,Aaron Maashoh,24,821-00-0265,Scientist,19114.12,1824.843333,3,...,4.0,Good,809.98,33.053114,22 Years and 10 Months,No,49.574949,21.465380264657146,High_spent_Medium_value_payments,361.44400385378196
2,0x160c,CUS_0xd40,November,Aaron Maashoh,24,821-00-0265,Scientist,19114.12,1824.843333,3,...,4.0,Good,809.98,33.811894,NaN,No,49.574949,148.23393788500925,Low_spent_Medium_value_payments,264.67544623342997
3,0x160d,CUS_0xd40,December,Aaron Maashoh,24_,821-00-0265,Scientist,19114.12,NaN,3,...,4.0,Good,809.98,32.430559,23 Years and 0 Months,No,49.574949,39.08251089460281,High_spent_Medium_value_payments,343.82687322383634
4,0x1616,CUS_0x21b1,September,Rick Rothackerj,28,004-07-5839,_______,34847.84,3037.986667,2,...,5.0,Good,605.03,25.926822,27 Years and 3 Months,No,18.816215,39.684018417945296,High_spent_Large_value_payments,485.2984336755923

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        50000 non-null  str
 1   Customer_ID               50000 non-null  str
 2   Month                     50000 non-null  str
 3   Name                      44985 non-null  str
 4   Age                       50000 non-null  str
 5   SSN                       50000 non-null  str
 6   Occupation                50000 non-null  str
 7   Annual_Income             50000 non-null  str
 8   Monthly_Inhand_Salary     42502 non-null  float64
 9   Num_Bank_Accounts         50000 non-null  int64
 10  Num_Credit_Card           50000 non-null  int64
 11  Interest_Rate             50000 non-null  int64
 12  Num_of_Loan               50000 non-null  str
 13  Type_of_Loan              44296 non-null  str
 14  Delay_from_due_date       50000 non-null  int64
 15  Num_of_Delayed_Payment    46502 non-null  str
 16  Changed_Credit_Limit      50000 non-null  str
 17  Num_Credit_Inquiries      48965 non-null  float64
 18  Credit_Mix                50000 non-null  str
 19  Outstanding_Debt          50000 non-null  str
 20  Credit_Utilization_Ratio  50000 non-null  float64
 21  Credit_History_Age        45530 non-null  str
 22  Payment_of_Min_Amount     50000 non-null  str
 23  Total_EMI_per_month       50000 non-null  float64
 24  Amount_invested_monthly   47729 non-null  str
 25  Payment_Behaviour         50000 non-null  str
 26  Monthly_Balance           49438 non-null  str
dtypes: float64(4), int64(4), str(19)
memory usage: 10.3 MB

Training set contains 100k rows and 28 cols, test set containes 50k rows and 27 cols.

'Credit_Score' is only present in the training data. It is the target and needs to be excluded from clustering inputs.

Some numeric fields such as 'Age', 'Annual_Income', and 'Outstanding_Debt' are stored as test and need to be looked at further to decide how they should be handled.

Multiple columns contain missing values including 'Monthly_Inhand_Salary', 'Type_of_Loan' and 'Credit_History_Age'

Some categoric fields contain placeholders such as '_' in 'Credit_Mix' and '_______' in 'Occupation'. Not being counted as missing by .info(). Will handle as missing.

The preview shows the same 'Customer_ID' across different months, Indicating that rows are observations of customer activity rather than specific unique customer entries. Will need to consider when splitting data.

In [26]:
# Handling numeric cols saved as strings

train_clean = train_data.copy()

numeric_string_cols = [
    "Age",
    "Annual_Income",
    "Num_of_Loan",
    "Num_of_Delayed_Payment",
    "Changed_Credit_Limit",
    "Outstanding_Debt",
    "Amount_invested_monthly",
    "Monthly_Balance"
]

# Looking at unique values in col that cant convert to numeric
for col in numeric_string_cols:
    values = train_data[col]
    converted = pd.to_numeric(values, errors="coerce")
    
    failed = values.notna() & converted.isna()
    
    print(f"\n{col}")
    print(values[failed].unique())

Age
<StringArray>
[  '28_',   '34_',   '30_',   '24_',   '33_',   '35_',   '31_',   '40_',
   '37_',   '54_',
 ...
 '7122_', '4913_', '5697_', '3843_', '4445_', '6921_',  '780_', '1070_',
 '5798_', '4808_']
Length: 127, dtype: str

Annual_Income
<StringArray>
[ '34847.84_',  '30689.89_',  '35547.71_',  '34081.38_', '114838.41_',
  '88640.24_',  '54392.16_',  '8701.545_',  '25546.26_',  '92047.08_',
 ...
  '39977.21_',  '10692.16_',  '64511.34_',  '41329.56_',  '20059.98_',
 '139664.96_',  '38321.39_',  '16680.35_',   '37188.1_',  '39628.99_']
Length: 5503, dtype: str

Num_of_Loan
<StringArray>
[   '0_',    '3_',    '2_',    '5_',    '8_',    '9_',    '4_',    '7_',
    '1_',    '6_',  '597_',   '92_', '1347_', '1185_',  '235_', '1459_',
 '1320_',  '630_',  '359_', '1225_',  '131_', '1311_', '1129_',  '785_',
  '143_', '1131_',   '27_', '1171_',  '227_',  '378_', '1219_',  '527_',
 '1027_',  '696_', '1132_']
Length: 35, dtype: str

Num_of_Delayed_Payment
<StringArray>
[   '8_',    '3_',    '2_',   '13_',   '14_',   '12_',   '22_',    '4_',
   '11_',   '21_',   '10_',  '183_',    '9_',   '19_',   '24_',   '17_',
   '23_',   '20_',    '6_',    '1_',   '16_',   '15_',   '26_',   '18_',
    '5_',   '25_',    '7_',    '0_', '2569_',   '27_',  '663_',   '-2_',
   '28_',   '-1_', '1323_', '2794_', '2219_',  '758_',   '-3_',  '848_',
 '2237_', '3097_', '2566_', '3840_', '2278_', '1087_', '1295_', '3861_',
 '2142_', '1473_', '3920_']
Length: 51, dtype: str

Changed_Credit_Limit
<StringArray>
['_']
Length: 1, dtype: str

Outstanding_Debt
<StringArray>
['1328.93_', '1283.37_', '2797.17_', '3818.57_',  '343.84_',  '363.51_',
  '404.51_', '1755.81_', '2593.44_',   '89.62_',
 ...
 '1321.46_',  '470.42_',  '111.75_',  '494.51_',  '807.65_', '4138.67_',
  '1095.9_', '1350.85_', '1453.61_',  '3571.7_']
Length: 975, dtype: str

Amount_invested_monthly
<StringArray>
['__10000__']
Length: 1, dtype: str

Monthly_Balance
['__-333333333333333333333333333__']

In [27]:
# values that can't convert are just numbers with '_' appended somewhere or just '_' by itself.
# Values with only '_' will be treated as missing.

train_clean = train_data.copy()

# Remove whitespace and underscores
for col in numeric_string_cols:
    values = train_clean[col].astype("string").str.strip().str.strip("_")
    train_clean[col] = pd.to_numeric(values, errors="coerce")
    
# Check
display(train_clean[numeric_string_cols].dtypes)
display(train_clean[numeric_string_cols].describe())

Age                          Int64
Annual_Income              Float64
Num_of_Loan                  Int64
Num_of_Delayed_Payment       Int64
Changed_Credit_Limit       Float64
Outstanding_Debt           Float64
Amount_invested_monthly    Float64
Monthly_Balance            Float64
dtype: object

,Age,Annual_Income,Num_of_Loan,Num_of_Delayed_Payment,Changed_Credit_Limit,Outstanding_Debt,Amount_invested_monthly,Monthly_Balance
count,100000.0,100000.0,100000.0,92998.0,97909.0,100000.0,95521.0,98800.0
mean,110.6497,176415.701298,3.00996,30.923342,10.389025,1426.220376,637.412998,-30364372469635625254912.0
std,686.244717,1429618.051414,62.647879,226.031892,6.789496,1155.129026,2043.319327,3181295008384102875267072.0
min,-500.0,7005.93,-100.0,-3.0,-6.49,0.23,0.0,-333333333333333314856026112.0
25%,24.0,19457.5,1.0,9.0,5.32,566.0725,74.534002,270.092209
50%,33.0,37578.61,3.0,14.0,9.4,1166.155,135.925682,336.71919
75%,42.0,72790.92,5.0,18.0,14.87,1945.9625,265.731733,470.220186
max,8698.0,24198062.0,1496.0,4397.0,36.97,4998.07,10000.0,1602.040519

There seems to be some invalid values in these columns still. 'Age' range goes from -500 to 8698, other cols contain impossible negative values. Some negative values are valid like those in 'Changed_Credit_Limit' corresponding to a credit decrease.

Most of these issues will be addressed by appying a valid range to each col. Clearly invalid values will be marked as missing.

In [28]:
# Handling invalid age range

questionable_ages = ~train_clean["Age"].between(0, 100)

print(f"Rows with questionable ages: ", questionable_ages.sum())
display(
    train_clean.loc[questionable_ages, "Age"]
    .value_counts()
    .sort_index()
)

# Looking for main age range
ages = train_clean["Age"]
print("Count of ages between 50 and 120:")
display(ages[ages.between(50,120)].value_counts().sort_index())
print("Count of ages below 18:")
display(train_clean.loc[train_clean["Age"] < 18, "Age"].value_counts().sort_index())

Rows with questionable ages:  2776

Age
-500    886
102       1
109       1
111       1
112       1
       ...
8674      1
8678      1
8682      1
8697      1
8698      1
Name: count, Length: 1682, dtype: Int64

Count of ages between 50 and 120:

Age
50     1273
51     1291
52     1356
53     1354
54     1311
55     1366
56      362
95        3
99        1
100       1
102       1
109       1
111       1
112       1
115       1
118       1
Name: count, dtype: Int64

Count of ages below 18:

Age
-500     886
14      1175
15      1574
16      1455
17      1502
Name: count, dtype: Int64

The main distribution of ages is in the range of 14 - 56, with no values from 57 - 94 and a few extreme values scattered beyond that. I will treat ages outside the 14 - 56 range as invalid. This may end up excluding genuine older customers.

To preserve the information these entries might have, I will impute the invalid ages. Removing could be a valid move considering the invalid ages make up around 2.7% of the total training set but I will go with imputing this time.

In [29]:
# Marking out of range ages as missing

invalid_age = (
    train_clean["Age"].notna()
    & ~train_clean["Age"].between(14,56)
)

print(f"Ages marked missing: {invalid_age.sum()} ({invalid_age.sum() / len(train_clean) * 100:.2f}%)")
train_clean.loc[invalid_age, "Age"] = pd.NA

print(f"Missing ages: {train_clean['Age'].isna().sum()}")

Ages marked missing: 2781 (2.78%)
Missing ages: 2781